defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: True
  waitkey: False
  tasks_per_scene: 20
scene_id: 3

# indexing params
decay_rate: 0.01
index_2d: False
init_categories: True
